In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/home/ammar/AI Track/Machine-Learning/Handling Mixed Variables/Datasets/titanic.csv")

In [3]:
df.head()

  Cabin            Ticket number  Survived
0   NaN         A/5 21171      5         0
1   C85          PC 17599      3         1
2   NaN  STON/O2. 3101282      6         1
3  C123            113803      3         1
4   NaN            373450      A         0

#### The number column has both numerical and categorical data
I will make two new columns from it

In [22]:
df['numerical_number'] = pd.to_numeric(df['number'], errors = 'coerce', downcast = 'integer' )
df['categorical_number'] = np.where(df['numerical_number'].isna(),df['number'],np.nan)

In [23]:
df.isna().sum()

Cabin                 687
Ticket                  0
number                  0
Survived                0
numerical_number      139
categorical_number    752
dtype: int64

In [24]:
df

,Cabin,Ticket,number,Survived,numerical_number,categorical_number
0,NaN,A/5 21171,5,0,5.0,NaN
1,C85,PC 17599,3,1,3.0,NaN
2,NaN,STON/O2. 3101282,6,1,6.0,NaN
3,C123,113803,3,1,3.0,NaN
4,NaN,373450,A,0,NaN,A
...,...,...,...,...,...,...
886,NaN,211536,3,0,3.0,NaN
887,B42,112053,3,1,3.0,NaN
888,NaN,W./C. 6607,1,0,1.0,NaN
889,C148,111369,2,1,2.0,NaN
890,NaN,370376,3,0,3.0,NaN

### Ticket column has both Categorical and Numerical data together in single cells
lets make new columns for this too

In [37]:
df['Ticket_Category'] = df['Ticket'].str.split().str.get(0)
df['Ticket_Number'] = df['Ticket'].str.split().str.get(1)

In [38]:
df

,Cabin,Ticket,number,Survived,numerical_number,categorical_number,Ticket_Category,Ticket_Number
0,NaN,A/5 21171,5,0,5.0,NaN,A/5,21171
1,C85,PC 17599,3,1,3.0,NaN,PC,17599
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,STON/O2.,3101282
3,C123,113803,3,1,3.0,NaN,113803,NaN
4,NaN,373450,A,0,NaN,A,373450,NaN
...,...,...,...,...,...,...,...,...
886,NaN,211536,3,0,3.0,NaN,211536,NaN
887,B42,112053,3,1,3.0,NaN,112053,NaN
888,NaN,W./C. 6607,1,0,1.0,NaN,W./C.,6607
889,C148,111369,2,1,2.0,NaN,111369,NaN
890,NaN,370376,3,0,3.0,NaN,370376,NaN